# .slsa-goreleaser.yml
# Configuration for SLSA3 Go releaser

version: 1

env:
  - CGO_ENABLED=0
  - GOOS=linux

main: ./main.go
dir: .
binary: cricket-collector
flags:
  - -trimpath
ldflags:
  - -s -w

goos: linux
goarch: amd64