name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build binaries
        run: |
          # Build for Linux amd64
          GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o cricket-collector-linux-amd64 main.go
          
          # Build for Linux arm64
          GOOS=linux GOARCH=arm64 go build -ldflags="-s -w" -o cricket-collector-linux-arm64 main.go
          
          # Build for Linux 386
          GOOS=linux GOARCH=386 go build -ldflags="-s -w" -o cricket-collector-linux-386 main.go

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            cricket-collector-linux-amd64
            cricket-collector-linux-arm64
            cricket-collector-linux-386
          generate_release_notes: true